name: Build solution

on:
  workflow_dispatch:

jobs:
  build-solution:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/GithubActionDemo.sln
    - name: Build
      run: dotnet build --no-restore ./src/GithubActionDemo.sln
