name: Deploy solution

on:
  workflow_run:
    workflows: ["Test solution"]
    types:
      - completed

jobs:
  test-solution:
    runs-on: ubuntu-latest

    steps:
    - name: Display result of "Test solution"
      run: |
          echo "Build solution result: ${{ github.event.workflow_run.conclusion }}"
    - name: "Deploy"
      run: |
          echo "Execute code to deploy"
    
