name: Deploy solution

on:
  workflow_run:
    workflows: ["Test solution"]
    types:
      - completed

jobs:
  deploy-solution:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: "Deploy"
      run: |
          echo "Execute code to deploy"    
