name: Test solution

on:
  workflow_run:
    workflows: ["Build solution"]
    types:
      - completed

jobs:
  test-solution:
    runs-on: ubuntu-latest

    steps:
    - name: Display result of "Build solution"
      run: |
          echo "Build solution result: ${{ github.event.workflow_run.conclusion }}"
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Test
      run: dotnet test ./src/GithubActionDemo.sln --verbosity normal
